"""add jury_ballots and malicious_tags tables, voided status

Revision ID: 0df90d670def
Revises: d2317be15ed0
Create Date: 2026-02-27 22:16:10.924961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df90d670def'
down_revision: Union[str, Sequence[str], None] = 'd2317be15ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jury_ballots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('arbiter_user_id', sa.String(), nullable=False),
    sa.Column('winner_submission_id', sa.String(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('coherence_status', sa.String(), nullable=True),
    sa.Column('is_majority', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['arbiter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['winner_submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'arbiter_user_id')
    )
    op.create_table('malicious_tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('arbiter_user_id', sa.String(), nullable=False),
    sa.Column('target_submission_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['arbiter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'arbiter_user_id', 'target_submission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('malicious_tags')
    op.drop_table('jury_ballots')
    # ### end Alembic commands ###
