"""add oracle v2 fields

Revision ID: 31bcc748a94b
Revises: eec967366a22
Create Date: 2026-02-25 17:54:31.624062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31bcc748a94b'
down_revision: Union[str, Sequence[str], None] = 'eec967366a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_dimensions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('dim_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dim_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('scoring_guidance', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('pending', 'gate_passed', 'gate_failed', 'scored', name='submissionstatus'),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acceptance_criteria', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('open', 'scoring', 'challenge_window', 'arbitrating', 'closed', name='taskstatus'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('credit_score',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(100.0)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('credit_score',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(100.0)'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('open', 'scoring', 'challenge_window', 'arbitrating', 'closed', name='taskstatus'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
        batch_op.drop_column('acceptance_criteria')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'gate_passed', 'gate_failed', 'scored', name='submissionstatus'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    op.drop_table('scoring_dimensions')
    # ### end Alembic commands ###
