"""add refund fields

Revision ID: 502439c9b548
Revises: 31bcc748a94b
Create Date: 2026-02-25 23:13:01.690748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502439c9b548'
down_revision: Union[str, Sequence[str], None] = '31bcc748a94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if 'arbiter_votes' not in existing_tables:
        op.create_table('arbiter_votes',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('challenge_id', sa.String(), nullable=False),
        sa.Column('arbiter_user_id', sa.String(), nullable=False),
        sa.Column('vote', sa.Enum('upheld', 'rejected', 'malicious', name='challengeverdict'), nullable=True),
        sa.Column('feedback', sa.Text(), nullable=True),
        sa.Column('is_majority', sa.Boolean(), nullable=True),
        sa.Column('reward_amount', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if 'stake_records' not in existing_tables:
        op.create_table('stake_records',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('purpose', sa.Enum('arbiter_deposit', 'credit_recharge', name='stakepurpose'), nullable=False),
        sa.Column('tx_hash', sa.String(), nullable=True),
        sa.Column('slashed', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if 'trust_events' not in existing_tables:
        op.create_table('trust_events',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('event_type', sa.Enum('worker_won', 'worker_consolation', 'worker_malicious', 'challenger_won', 'challenger_rejected', 'challenger_malicious', 'arbiter_majority', 'arbiter_minority', 'arbiter_timeout', 'github_bind', 'weekly_leaderboard', 'stake_bonus', 'stake_slash', name='trusteventtype'), nullable=False),
        sa.Column('task_id', sa.String(), nullable=True),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('delta', sa.Float(), nullable=False),
        sa.Column('score_before', sa.Float(), nullable=False),
        sa.Column('score_after', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )

    # PostgreSQL: 需要显式 ADD VALUE 到已有 Enum 类型，以及提前 CREATE TYPE
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("ALTER TYPE payoutstatus ADD VALUE IF NOT EXISTS 'refunded'")
        sa.Enum('S', 'A', 'B', 'C', name='trusttier').create(bind, checkfirst=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refund_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('refund_tx_hash', sa.String(), nullable=True))
        batch_op.alter_column('payout_status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('pending', 'paid', 'failed', 'refunded', name='payoutstatus'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trust_score', sa.Float(), nullable=False, server_default='500.0'))
        batch_op.add_column(sa.Column('trust_tier', sa.Enum('S', 'A', 'B', 'C', name='trusttier'), nullable=False, server_default='A'))
        batch_op.add_column(sa.Column('github_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('github_bonus_claimed', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('consolation_total', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('is_arbiter', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('staked_amount', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('stake_bonus', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.drop_column('credit_score')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_score', sa.FLOAT(), nullable=False))
        batch_op.drop_column('stake_bonus')
        batch_op.drop_column('staked_amount')
        batch_op.drop_column('is_arbiter')
        batch_op.drop_column('consolation_total')
        batch_op.drop_column('github_bonus_claimed')
        batch_op.drop_column('github_id')
        batch_op.drop_column('trust_tier')
        batch_op.drop_column('trust_score')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('payout_status',
               existing_type=sa.Enum('pending', 'paid', 'failed', 'refunded', name='payoutstatus'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('refund_tx_hash')
        batch_op.drop_column('refund_amount')

    op.drop_table('trust_events')
    op.drop_table('stake_records')
    op.drop_table('arbiter_votes')
    # ### end Alembic commands ###
