"""add arbiter hawkish trust event types

Revision ID: b34fa3d8a582
Revises: 0df90d670def
Create Date: 2026-02-27 23:27:03.576857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34fa3d8a582'
down_revision: Union[str, Sequence[str], None] = '0df90d670def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # PostgreSQL: 补全 taskstatus 的 voided 值和 trusteventtype 的新值
    # SQLite 以字符串方式存储 Enum，无需 DDL
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("ALTER TYPE taskstatus ADD VALUE IF NOT EXISTS 'voided'")
        op.execute("ALTER TYPE trusteventtype ADD VALUE IF NOT EXISTS 'publisher_completed'")
        op.execute("ALTER TYPE trusteventtype ADD VALUE IF NOT EXISTS 'arbiter_coherence'")
        op.execute("ALTER TYPE trusteventtype ADD VALUE IF NOT EXISTS 'pw_malicious'")
        op.execute("ALTER TYPE trusteventtype ADD VALUE IF NOT EXISTS 'challenger_justified'")
        op.execute("ALTER TYPE trusteventtype ADD VALUE IF NOT EXISTS 'arbiter_tp_malicious'")
        op.execute("ALTER TYPE trusteventtype ADD VALUE IF NOT EXISTS 'arbiter_fp_malicious'")
        op.execute("ALTER TYPE trusteventtype ADD VALUE IF NOT EXISTS 'arbiter_fn_malicious'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
