"""add coherence_status to arbiter_votes

Revision ID: b8740cdc8634
Revises: a188e679ba7a
Create Date: 2026-02-27 00:42:27.040017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8740cdc8634'
down_revision: Union[str, Sequence[str], None] = 'a188e679ba7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arbiter_votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coherence_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arbiter_votes', schema=None) as batch_op:
        batch_op.drop_column('coherence_status')

    # ### end Alembic commands ###
