"""add policy_violation submission status

Revision ID: bb58022f4efe
Revises: b8740cdc8634
Create Date: 2026-02-27 16:49:25.279473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb58022f4efe'
down_revision: Union[str, Sequence[str], None] = 'b8740cdc8634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('pending', 'gate_passed', 'gate_failed', 'scored', 'policy_violation', name='submissionstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'gate_passed', 'gate_failed', 'scored', 'policy_violation', name='submissionstatus'),
               type_=sa.Enum('pending', 'gate_passed', 'gate_failed', 'scored', name='submissionstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###
