"""init schema

Revision ID: eec967366a22
Revises: 
Create Date: 2026-02-24 22:40:03.373266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec967366a22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('challenger_submission_id', sa.String(), nullable=False),
    sa.Column('target_submission_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('verdict', sa.Enum('upheld', 'rejected', 'malicious', name='challengeverdict'), nullable=True),
    sa.Column('arbiter_feedback', sa.Text(), nullable=True),
    sa.Column('arbiter_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'judged', name='challengestatus'), nullable=False),
    sa.Column('challenger_wallet', sa.String(), nullable=True),
    sa.Column('deposit_tx_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('oracle_feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'scored', name='submissionstatus'), nullable=False),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.Column('deposit_returned', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('fastest_first', 'quality_first', name='tasktype'), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('max_revisions', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'scoring', 'challenge_window', 'arbitrating', 'closed', name='taskstatus'), nullable=False),
    sa.Column('winner_submission_id', sa.String(), nullable=True),
    sa.Column('publisher_id', sa.String(), nullable=True),
    sa.Column('bounty', sa.Float(), nullable=True),
    sa.Column('payment_tx_hash', sa.String(), nullable=True),
    sa.Column('payout_status', sa.Enum('pending', 'paid', 'failed', name='payoutstatus'), nullable=False),
    sa.Column('payout_tx_hash', sa.String(), nullable=True),
    sa.Column('payout_amount', sa.Float(), nullable=True),
    sa.Column('submission_deposit', sa.Float(), nullable=True),
    sa.Column('challenge_duration', sa.Integer(), nullable=True),
    sa.Column('challenge_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('wallet', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('publisher', 'worker', 'both', name='userrole'), nullable=False),
    sa.Column('credit_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('submissions')
    op.drop_table('challenges')
    # ### end Alembic commands ###
